[project]
name = "jsut-recorder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "gradio>=4.44.1",
    "librosa>=0.10.2.post1",
    "sounddevice>=0.5.1",
    "soundfile>=0.12.1",
]
