[project]
name = "jsut-recorder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "sounddevice>=0.5.1",
    "wave>=0.0.2",
]
